# -*- coding: utf-8 -*-
"""Prados del Refugio (Dashboard y Chatbot) Post Sismo .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JvN-QPU2ZVEjy1J6LfK-xakvQYNy8PYJ
"""

!pip install -q streamlit plotly pandas

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# from datetime import datetime
# import os
# import numpy as np
# import pandas as pd
# import plotly.express as px
# import streamlit as st
# 
# st.set_page_config(
#     page_title="Prados del Refugio | PMU",
#     layout="wide",
#     initial_sidebar_state="expanded",
# )
# 
# # Estética institucional minimalista (Inspiración ProPacífico)
# st.markdown(
#     """
#     <style>
#     @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&family=Playfair+Display:ital,wght@0,600;1,400&display=swap');
# 
#     html, body, [class*="css"] {
#         font-family: 'Montserrat', sans-serif;
#         color: #2b2b2b;
#     }
# 
#     .hero-banner {
#         background: linear-gradient(135deg, #1f2421 0%, #2f3e46 60%, #e05a2b 100%);
#         padding: 36px 44px;
#         border-radius: 4px;
#         color: white;
#         margin-bottom: 28px;
#     }
#     .hero-title {
#         font-family: 'Playfair Display', serif;
#         font-size: 30px;
#         font-weight: 600;
#         letter-spacing: -0.5px;
#         margin: 0;
#         color: #ffffff !important;
#     }
#     .hero-subtitle {
#         font-size: 13px;
#         font-weight: 300;
#         letter-spacing: 1.5px;
#         text-transform: uppercase;
#         color: #f4a261;
#         margin-top: 6px;
#     }
# 
#     .kpi-container {
#         background-color: #ffffff;
#         border-top: 3px solid #e05a2b;
#         border-left: 1px solid #e9ecef;
#         border-right: 1px solid #e9ecef;
#         border-bottom: 1px solid #e9ecef;
#         padding: 20px 22px;
#         border-radius: 2px;
#         box-shadow: 0 1px 3px rgba(0,0,0,0.04);
#     }
#     .kpi-label {
#         font-size: 11px;
#         font-weight: 600;
#         letter-spacing: 1px;
#         text-transform: uppercase;
#         color: #6c757d;
#     }
#     .kpi-value {
#         font-size: 26px;
#         font-weight: 700;
#         color: #1f2421;
#         margin-top: 4px;
#     }
#     .kpi-sub {
#         font-size: 12px;
#         color: #e05a2b;
#         font-weight: 500;
#         margin-top: 4px;
#     }
# 
#     section[data-testid="stSidebar"] {
#         background-color: #f8f9fa;
#         border-right: 1px solid #e9ecef;
#     }
# 
#     /* Semáforo Operativo */
#     .traffic-card {
#         background: #ffffff;
#         border: 1px solid #e9ecef;
#         border-radius: 3px;
#         padding: 20px 22px;
#         margin-bottom: 16px;
#         box-shadow: 0 1px 3px rgba(0,0,0,0.02);
#     }
#     .traffic-header {
#         font-size: 12px;
#         font-weight: 700;
#         letter-spacing: 1.2px;
#         text-transform: uppercase;
#         margin-bottom: 12px;
#         display: flex;
#         align-items: center;
#     }
#     .dot-urgent { width: 10px; height: 10px; background-color: #c92a2a; border-radius: 50%; display: inline-block; margin-right: 8px; }
#     .dot-process { width: 10px; height: 10px; background-color: #f59f00; border-radius: 50%; display: inline-block; margin-right: 8px; }
#     .dot-done { width: 10px; height: 10px; background-color: #2b8a3e; border-radius: 50%; display: inline-block; margin-right: 8px; }
#     .text-urgent { color: #c92a2a; }
#     .text-process { color: #d97706; }
#     .text-done { color: #2b8a3e; }
# 
#     .traffic-list {
#         font-size: 13px;
#         color: #495057;
#         line-height: 1.8;
#         margin: 0;
#         padding-left: 18px;
#     }
# 
#     /* Habeas Data Banner */
#     .legal-card {
#         background-color: #fdfbf7;
#         border-left: 3px solid #868e96;
#         border-top: 1px solid #e9ecef;
#         border-right: 1px solid #e9ecef;
#         border-bottom: 1px solid #e9ecef;
#         padding: 16px 20px;
#         margin-top: 30px;
#         border-radius: 2px;
#     }
#     .legal-title {
#         font-size: 11px;
#         font-weight: 700;
#         letter-spacing: 1px;
#         text-transform: uppercase;
#         color: #495057;
#         margin-bottom: 4px;
#     }
#     .legal-text {
#         font-size: 12px;
#         color: #6c757d;
#         line-height: 1.5;
#         margin: 0;
#     }
#     </style>
# """,
#     unsafe_allow_html=True,
# )
# 
# # -------------------------------------------------------------
# # GESTIÓN DE BASE DE DATOS Y PERSISTENCIA
# # -------------------------------------------------------------
# ARCHIVO_INSCRIPCIONES = "inscripciones_voluntarios.csv"
# 
# 
# def guardar_inscripcion(
#     nombre, torre, apto, telefono, profesion, mesa, disponibilidad
# ):
#   registro = {
#       "Fecha_Registro": [datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
#       "Nombre_Completo": [nombre],
#       "Torre": [torre],
#       "Apartamento": [apto],
#       "Telefono": [telefono],
#       "Profesion_Habilidad": [profesion],
#       "Mesa_Asignada": [mesa],
#       "Disponibilidad": [disponibilidad],
#   }
#   df_nuevo = pd.DataFrame(registro)
# 
#   if os.path.exists(ARCHIVO_INSCRIPCIONES):
#     df_existente = pd.read_csv(ARCHIVO_INSCRIPCIONES)
#     df_final = pd.concat([df_existente, df_nuevo], ignore_index=True)
#   else:
#     df_final = df_nuevo
# 
#   df_final.to_csv(ARCHIVO_INSCRIPCIONES, index=False)
#   return df_final
# 
# 
# def cargar_inscripciones():
#   if os.path.exists(ARCHIVO_INSCRIPCIONES):
#     return pd.read_csv(ARCHIVO_INSCRIPCIONES)
#   else:
#     return pd.DataFrame(columns=[
#         "Fecha_Registro",
#         "Nombre_Completo",
#         "Torre",
#         "Apartamento",
#         "Telefono",
#         "Profesion_Habilidad",
#         "Mesa_Asignada",
#         "Disponibilidad",
#     ])
# 
# 
# # Datos base del censo
# def generar_datos_base():
#   np.random.seed(42)
#   aptos_a = [f"{piso}0{num}" for piso in range(1, 6) for num in range(1, 5)]
#   aptos_b = [f"{piso}0{num}" for piso in range(1, 6) for num in range(1, 5)]
#   aptos_c = [f"{piso}0{num}" for piso in range(1, 7) for num in range(1, 5)]
# 
#   registros = []
#   for a in aptos_a:
#     registros.append({"torre": "Torre A", "unidad": a, "tipo": "Privado"})
#   for b in aptos_b:
#     registros.append({"torre": "Torre B", "unidad": b, "tipo": "Privado"})
#   for c in aptos_c:
#     registros.append({"torre": "Torre C", "unidad": c, "tipo": "Privado"})
# 
#   df_p = pd.DataFrame(registros)
#   n = len(df_p)
# 
#   df_p["propietario"] = [f"Residente {i}" for i in range(1, n + 1)]
#   df_p["cedula"] = [
#       f"{np.random.randint(10000000, 99999999)}" for _ in range(n)
#   ]
#   df_p["telefono"] = [
#       f"3{np.random.randint(100000000, 999999999)}" for _ in range(n)
#   ]
#   df_p["correo"] = [f"contacto{i}@prados.com" for i in range(1, n + 1)]
#   df_p["hubo_lesionados"] = np.random.choice(["Sí", "No"], n, p=[0.04, 0.96])
#   df_p["tipo_lesion"] = df_p["hubo_lesionados"].apply(
#       lambda x: (
#           np.random.choice(
#               ["Contusión leve", "Corte superficial", "Ansiedad aguda"]
#           )
#           if x == "Sí"
#           else "Ninguna"
#       )
#   )
#   df_p["inmueble_afectado"] = np.random.choice(
#       ["Sí", "No"], n, p=[0.52, 0.48]
#   )
#   df_p["autoriza_datos"] = np.random.choice(["Sí", "No"], n, p=[0.94, 0.06])
# 
#   comunes = [
#       "Pasillos",
#       "Portería",
#       "Gradas",
#       "Parqueadero",
#       "Salón Social",
#       "Piscina",
#   ]
#   registros_c = []
#   for com in comunes:
#     registros_c.append({
#         "torre": "Áreas Comunes",
#         "unidad": com,
#         "tipo": "Común",
#         "propietario": "Administración General",
#         "cedula": "NIT Copropiedad",
#         "telefono": "PBX Principal",
#         "correo": "admin@pradosdelrefugio.com",
#         "hubo_lesionados": "No",
#         "tipo_lesion": "Ninguna",
#         "inmueble_afectado": np.random.choice(["Sí", "No"], p=[0.5, 0.5]),
#         "autoriza_datos": "Sí",
#     })
#   df_c = pd.DataFrame(registros_c)
#   return pd.concat([df_p, df_c], ignore_index=True)
# 
# 
# @st.cache_data
# def cargar_datos():
#   if os.path.exists("resultados.csv"):
#     return pd.read_csv("resultados.csv")
#   else:
#     return generar_datos_base()
# 
# 
# df = cargar_datos()
# df_priv = df[df["tipo"] == "Privado"]
# df_com = df[df["tipo"] == "Común"]
# 
# # Menú lateral
# st.sidebar.markdown(
#     """
#     <div style="padding: 10px 0 20px 0;">
#         <span style="font-family: 'Playfair Display', serif; font-size: 20px; font-weight: 700; color: #1f2421;">Prados del Refugio</span><br>
#         <span style="font-size: 11px; color: #e05a2b; letter-spacing: 1px; text-transform: uppercase;">Puesto de Mando Unificado</span>
#     </div>
# """,
#     unsafe_allow_html=True,
# )
# 
# pagina = st.sidebar.radio(
#     "Módulos de Información",
#     [
#         "Panel de Control y Diagnóstico",
#         "Participa en la Recuperación",
#         "Póliza y Reclamación de Seguros",
#         "Planos Estructurales e Inspección",
#         "Asistente Virtual",
#     ],
# )
# 
# # Header Global
# st.markdown(
#     """
#     <div class="hero-banner">
#         <div class="hero-title">Conjunto Residencial Prados del Refugio</div>
#         <div class="hero-subtitle">Sistema Integrado de Información Post-Sismo · Cali</div>
#     </div>
# """,
#     unsafe_allow_html=True,
# )
# 
# # -------------------------------------------------------------
# # 1. PANEL DE CONTROL Y DIAGNÓSTICO
# # -------------------------------------------------------------
# if pagina == "Panel de Control y Diagnóstico":
#   c1, c2, c3, c4 = st.columns(4)
#   total_censados = len(df_priv)
#   afectados_aptos = (df_priv["inmueble_afectado"] == "Sí").sum()
#   afectados_comunes = (df_com["inmueble_afectado"] == "Sí").sum()
#   lesionados = (df["hubo_lesionados"] == "Sí").sum()
# 
#   with c1:
#     st.markdown(
#         f"""
#             <div class="kpi-container">
#                 <div class="kpi-label">Censo Unidades Privadas</div>
#                 <div class="kpi-value">{total_censados}</div>
#                 <div class="kpi-sub">Torres A (5p), B (5p), C (6p)</div>
#             </div>
#         """,
#         unsafe_allow_html=True,
#     )
#   with c2:
#     st.markdown(
#         f"""
#             <div class="kpi-container">
#                 <div class="kpi-label">Inmuebles con Afectación</div>
#                 <div class="kpi-value">{afectados_aptos}</div>
#                 <div class="kpi-sub">{round(afectados_aptos/total_censados*100)}% del total censado</div>
#             </div>
#         """,
#         unsafe_allow_html=True,
#     )
#   with c3:
#     st.markdown(
#         f"""
#             <div class="kpi-container">
#                 <div class="kpi-label">Zonas Comunes Afectadas</div>
#                 <div class="kpi-value">{afectados_comunes} / {len(df_com)}</div>
#                 <div class="kpi-sub">Evaluación locativa</div>
#             </div>
#         """,
#         unsafe_allow_html=True,
#     )
#   with c4:
#     st.markdown(
#         f"""
#             <div class="kpi-container">
#                 <div class="kpi-label">Atención en Salud</div>
#                 <div class="kpi-value">{lesionados}</div>
#                 <div class="kpi-sub">Prioridad asistencial</div>
#             </div>
#         """,
#         unsafe_allow_html=True,
#     )
# 
#   st.write("")
#   st.write("")
# 
#   g1, g2 = st.columns(2)
#   with g1:
#     df_torres = (
#         df_priv.groupby(["torre", "inmueble_afectado"])
#         .size()
#         .reset_index(name="conteo")
#     )
#     fig1 = px.bar(
#         df_torres,
#         x="torre",
#         y="conteo",
#         color="inmueble_afectado",
#         title="Consolidado de Afectaciones por Torre",
#         barmode="stack",
#         color_discrete_map={"Sí": "#e05a2b", "No": "#2f3e46"},
#         category_orders={"torre": ["Torre A", "Torre B", "Torre C"]},
#     )
#     fig1.update_layout(
#         paper_bgcolor="rgba(0,0,0,0)",
#         plot_bgcolor="rgba(0,0,0,0)",
#         font=dict(family="Montserrat", size=12),
#         legend_title_text="Reporte Daño",
#     )
#     st.plotly_chart(fig1, use_container_width=True)
# 
#   with g2:
#     fig2 = px.bar(
#         df_com,
#         x="unidad",
#         y="inmueble_afectado",
#         title="Diagnóstico Técnico en Áreas Comunes",
#         color="inmueble_afectado",
#         color_discrete_map={"Sí": "#e05a2b", "No": "#2f3e46"},
#     )
#     fig2.update_layout(
#         paper_bgcolor="rgba(0,0,0,0)",
#         plot_bgcolor="rgba(0,0,0,0)",
#         font=dict(family="Montserrat", size=12),
#         xaxis_title="",
#         yaxis_title="",
#         legend_title_text="Afectación",
#     )
#     st.plotly_chart(fig2, use_container_width=True)
# 
#   st.write("---")
#   st.subheader("Detalle Nominal de Inmuebles")
#   st.caption(
#       "Filtro por bloque estructural con resguardo estricto de Habeas Data."
#   )
#   torre_sel = st.selectbox(
#       "Seleccionar Bloque:", ["Torre A", "Torre B", "Torre C"]
#   )
#   df_vista = df_priv[df_priv["torre"] == torre_sel][[
#       "unidad",
#       "inmueble_afectado",
#       "hubo_lesionados",
#       "tipo_lesion",
#       "autoriza_datos",
#   ]].rename(
#       columns={
#           "unidad": "Apartamento",
#           "inmueble_afectado": "Afectación Reportada",
#           "hubo_lesionados": "Lesionados",
#           "tipo_lesion": "Diagnóstico Inicial",
#           "autoriza_datos": "Autorización Póliza",
#       }
#   )
#   st.dataframe(df_vista, use_container_width=True, hide_index=True)
# 
# # -------------------------------------------------------------
# # 2. PARTICIPA EN LA RECUPERACIÓN (FORMULARIO EN VIVO CON PERSISTENCIA)
# # -------------------------------------------------------------
# elif pagina == "Participa en la Recuperación":
#   st.subheader("Participa en la Recuperación del Conjunto")
#   st.markdown(
#       """
#         <p style="font-size: 14px; color: #495057; line-height: 1.6; margin-bottom: 24px;">
#             <b>La recuperación es responsabilidad de todos.</b><br>
#             Consulta el estado de avance de las tareas críticas e inscríbete en la mesa de trabajo donde desees aportar. Los registros quedan guardados directamente en la base de datos consolidada del PMU.
#         </p>
#     """,
#       unsafe_allow_html=True,
#   )
# 
#   # 1. SEMÁFORO OPERATIVO
#   st.markdown("#### Balance y Priorización de Tareas")
#   col_urg, col_proc, col_comp = st.columns(3)
# 
#   with col_urg:
#     st.markdown(
#         """
#             <div class="traffic-card" style="border-top: 3px solid #c92a2a;">
#                 <div class="traffic-header text-urgent"><span class="dot-urgent"></span>Urgente / Crítico</div>
#                 <ul class="traffic-list">
#                     <li>18 apartamentos aún no han diligenciado el censo.</li>
#                     <li>Falta documentación de 7 propietarios para el seguro.</li>
#                     <li>Pendiente inspección técnica en Torre B y C.</li>
#                     <li>Contacto prioritario a familias con reporte médico.</li>
#                 </ul>
#             </div>
#         """,
#         unsafe_allow_html=True,
#     )
# 
#   with col_proc:
#     st.markdown(
#         """
#             <div class="traffic-card" style="border-top: 3px solid #f59f00;">
#                 <div class="traffic-header text-process"><span class="dot-process"></span>En Proceso</div>
#                 <ul class="traffic-list">
#                     <li>Evaluación técnica de zonas comunes (piscina y gradas).</li>
#                     <li>Cotización de reparación de mampostería y fachada.</li>
#                     <li>Consolidación del archivo digital de reclamación.</li>
#                     <li>Revisión de acometidas e instalaciones de gas.</li>
#                 </ul>
#             </div>
#         """,
#         unsafe_allow_html=True,
#     )
# 
#   with col_comp:
#     st.markdown(
#         """
#             <div class="traffic-card" style="border-top: 3px solid #2b8a3e;">
#                 <div class="traffic-header text-done"><span class="dot-done"></span>Completado</div>
#                 <ul class="traffic-list">
#                     <li>Notificación formal de siniestro a la aseguradora.</li>
#                     <li>Censo inicial y habilitación de formulario en línea.</li>
#                     <li>Registro fotográfico preliminar de áreas comunes.</li>
#                     <li>Instalación del Puesto de Mando Unificado (PMU).</li>
#                 </ul>
#             </div>
#         """,
#         unsafe_allow_html=True,
#     )
# 
#   st.write("---")
# 
#   # 2. FORMULARIO DE INSCRIPCIÓN EN VIVO
#   st.markdown("#### Formulario de Postulación de Voluntarios")
#   st.caption(
#       "Diligencia tus datos para unirte como apoyo activo en las mesas de"
#       " trabajo."
#   )
# 
#   with st.form("form_inscripcion_voluntarios", clear_on_submit=True):
#     f_col1, f_col2, f_col3 = st.columns(3)
#     with f_col1:
#       nombre_input = st.text_input(
#           "Nombre y Apellidos *", placeholder="Ej: Melisa Espinosa"
#       )
#       torre_input = st.selectbox("Torre *", ["Torre A", "Torre B", "Torre C"])
#       apto_input = st.text_input("Apartamento *", placeholder="Ej: 401")
#     with f_col2:
#       tel_input = st.text_input(
#           "Teléfono de Contacto (WhatsApp) *", placeholder="Ej: 3151234567"
#       )
#       profesion_input = st.text_input(
#           "Profesión / Habilidad de Apoyo",
#           placeholder="Ej: Ingeniera / Científica de Datos / Logística",
#       )
#     with f_col3:
#       mesa_input = st.selectbox(
#           "Mesa en la que deseas participar *",
#           [
#               "Seguros y Siniestros",
#               "Censo y Caracterización",
#               "Reconstrucción e Infraestructura",
#               "Comunicaciones y Atención a Residentes",
#               "Finanzas y Recursos",
#               "Limpieza y Habitabilidad",
#           ],
#       )
#       disp_input = st.selectbox(
#           "Disponibilidad *",
#           [
#               "Tiempo Parcial (Tardes / Fines de Semana)",
#               "Tiempo Completo (Presencial en PMU)",
#               "Apoyo Remoto / Digital",
#           ],
#       )
# 
#     acepta_datos = st.checkbox(
#         "Autorizo el tratamiento de mis datos personales para la coordinación"
#         " de la emergencia (Ley 1581/2012) *"
#     )
# 
#     btn_enviar = st.form_submit_button(
#         "Confirmar Inscripción en Mesa de Trabajo"
#     )
# 
#     if btn_enviar:
#       if not nombre_input or not apto_input or not tel_input:
#         st.error("Por favor completa los campos obligatorios marcados con *.")
#       elif not acepta_datos:
#         st.warning(
#             "Debes autorizar el tratamiento de datos para registrar tu"
#             " postulación."
#         )
#       else:
#         guardar_inscripcion(
#             nombre_input,
#             torre_input,
#             apto_input,
#             tel_input,
#             profesion_input,
#             mesa_input,
#             disp_input,
#         )
#         st.success(
#             f"¡Gracias, {nombre_input}! Tu postulación para la mesa de"
#             f" '{mesa_input}' ha sido registrada con éxito en el sistema."
#         )
# 
#   st.write("---")
# 
#   # 3. LISTADO EN VIVO DE VOLUNTARIOS REGISTRADOS
#   st.markdown("#### Registro Consolidado de Voluntarios Inscritos")
#   df_voluntarios = cargar_inscripciones()
# 
#   if len(df_voluntarios) > 0:
#     st.caption(
#         f"Total personas registradas en tiempo real: {len(df_voluntarios)}"
#     )
#     vista_publica_vol = df_voluntarios[[
#         "Fecha_Registro",
#         "Nombre_Completo",
#         "Torre",
#         "Apartamento",
#         "Mesa_Asignada",
#         "Disponibilidad",
#     ]]
#     st.dataframe(vista_publica_vol, use_container_width=True, hide_index=True)
# 
#     csv_vol = df_voluntarios.to_csv(index=False).encode("utf-8")
#     st.download_button(
#         label="Descargar Base Consolidada de Voluntarios (CSV)",
#         data=csv_vol,
#         file_name="Voluntarios_PMU_Prados_del_Refugio.csv",
#         mime="text/csv",
#     )
#   else:
#     st.info(
#         "Aún no hay registros en la base de voluntarios. Diligencia el"
#         " formulario superior para postularte."
#     )
# 
# # -------------------------------------------------------------
# # 3. PÓLIZA Y RECLAMACIÓN DE SEGUROS
# # -------------------------------------------------------------
# elif pagina == "Póliza y Reclamación de Seguros":
#   st.subheader("Gestión y Trámite de Póliza Colectiva")
#   st.write(
#       "Lineamientos técnicos y normativos para la radicación del siniestro"
#       " ante la compañía aseguradora."
#   )
# 
#   c_p1, c_p2 = st.columns([1, 1])
#   with c_p1:
#     st.markdown("""
#             ### Ficha Técnica de la Póliza
#             * **Aseguradora:** Seguros del Estado / Copropiedades
#             * **Régimen:** Póliza de Zonas Comunes y Privadas con Amparo de Terremoto
#             * **Vigencia:** 2026 - 2027
#             * **Deducible Sismo:** 10% del valor de la pérdida con mínimo legal
#             * **Estado:** Aviso de siniestro emitido formalmente
#         """)
#   with c_p2:
#     st.markdown("""
#             ### Protocolo de Integración de Expedientes
#             1. **Consolidación del Censo:** Cierre formal del censo de afectaciones locativas.
#             2. **Filtro de Habeas Data:** Inclusión estricta de propietarios con autorización digital firmada.
#             3. **Inspección de Ajuste:** Visita del perito designado para evaluación técnica en sitio.
#             4. **Dictamen Estructural:** Emisión de acta de liquidación y cronograma de resarcimiento.
#         """)
# 
#   st.write("---")
#   st.subheader("Expediente para Radicación al Ajustador")
#   df_seguro = df[
#       (df["inmueble_afectado"] == "Sí") & (df["autoriza_datos"] == "Sí")
#   ][["torre", "unidad", "propietario", "cedula", "telefono", "correo"]]
#   st.caption(
#       f"Total registros listos para radicación inmediata: {len(df_seguro)}"
#       " inmuebles."
#   )
#   st.dataframe(df_seguro, use_container_width=True, hide_index=True)
# 
#   csv_exp = df_seguro.to_csv(index=False).encode("utf-8")
#   st.download_button(
#       label="Descargar Expediente Consolidado (CSV)",
#       data=csv_exp,
#       file_name="Expediente_Seguros_Prados_del_Refugio.csv",
#       mime="text/csv",
#   )
# 
# # -------------------------------------------------------------
# # 4. PLANOS ESTRUCTURALES E INSPECCIÓN
# # -------------------------------------------------------------
# elif pagina == "Planos Estructurales e Inspección":
#   st.subheader("Planos Estructurales y Puntos Críticos de Inspección")
#   st.write(
#       "Consulte la distribución por niveles de las Torres A, B y C junto a las"
#       " directrices de revisión de mampostería y estructura portante."
#   )
# 
#   torre_plano = st.selectbox(
#       "Seleccionar Plano por Bloque:",
#       [
#           "Torre A (5 Niveles - Sistema Aporticado)",
#           "Torre B (5 Niveles - Sistema Aporticado)",
#           "Torre C (6 Niveles - Sistema Aporticado / Muros de Corte)",
#       ],
#   )
# 
#   col_plano, col_crit = st.columns([1.4, 1])
# 
#   with col_plano:
#     if "Torre A" in torre_plano or "Torre B" in torre_plano:
#       pisos = [f"Nivel {i}" for i in range(5, 0, -1)]
#     else:
#       pisos = [f"Nivel {i}" for i in range(6, 0, -1)]
# 
#     fig_ele = px.bar(
#         x=[4] * len(pisos),
#         y=pisos,
#         orientation="h",
#         title=f"Elevación Esquemática - {torre_plano.split(' (')[0]}",
#         labels={"x": "Unidades por Nivel", "y": "Piso"},
#         color_discrete_sequence=["#2f3e46"],
#     )
#     fig_ele.update_layout(
#         paper_bgcolor="rgba(0,0,0,0)",
#         plot_bgcolor="rgba(0,0,0,0)",
#         font=dict(family="Montserrat", size=12),
#     )
#     st.plotly_chart(fig_ele, use_container_width=True)
# 
#   with col_crit:
#     st.markdown("""
#             ### Puntos de Control Técnico
#             * **Juntas de Dilatación:** Verificación de separación libre entre bloques.
#             * **Caja de Gradas:** Inspección de muros divisorios no estructurales.
#             * **Paredes de Mampostería:** Registro de fisuras diagonales a 45° vs. fisuras superficiales de estuco.
#             * **Redes Hidrosanitarias:** Comprobación de integridad en bajantes principales de aguas servidas.
#         """)
# 
# # -------------------------------------------------------------
# # 5. ASISTENTE VIRTUAL
# # -------------------------------------------------------------
# elif pagina == "Asistente Virtual":
#   st.subheader("💬 Asistente Comunitario")
#   st.caption(
#       "Consulte en lenguaje natural el estado de su torre, áreas comunes,"
#       " póliza o cómo inscribirse como voluntario."
#   )
# 
#   if "mensajes" not in st.session_state:
#     st.session_state.mensajes = [{
#         "role": "assistant",
#         "content": (
#             "Buenas tardes. Soy el asistente oficial de Prados del Refugio."
#             " ¿En qué información sobre las torres, póliza de seguro, tareas"
#             " pendientes o inscripción en mesas de trabajo puedo orientarle?"
#         ),
#     }]
# 
#   for msg in st.session_state.mensajes:
#     with st.chat_message(msg["role"]):
#       st.write(msg["content"])
# 
#   if prompt := st.chat_input(
#       "Escriba su consulta (ej: ¿Cómo me inscribo en una mesa? ¿Qué tareas"
#       " urgentes hay?)"
#   ):
#     st.session_state.mensajes.append({"role": "user", "content": prompt})
#     with st.chat_message("user"):
#       st.write(prompt)
# 
#     p_low = prompt.lower()
#     if (
#         "inscrib" in p_low
#         or "postular" in p_low
#         or "participar" in p_low
#         or "voluntari" in p_low
#     ):
#       resp = (
#           "Puedes inscribirte directamente en la sección 'Participa en la"
#           " Recuperación'. Allí encontrarás el formulario oficial para"
#           " registrar tu nombre, torre, apartamento, profesión y mesa de"
#           " interés."
#       )
#     elif "urgente" in p_low or "semaforo" in p_low or "pendiente" in p_low:
#       resp = (
#           "En el semáforo operativo tenemos como URGENTE: completar el censo"
#           " en 18 apartamentos faltantes, radicar documentos de 7"
#           " copropietarios para el seguro y finalizar la inspección técnica en"
#           " bloques."
#       )
#     elif "poliza" in p_low or "seguro" in p_low or "aseguradora" in p_low:
#       resp = (
#           "El trámite de póliza se encuentra consolidando el expediente con las"
#           " firmas de autorización para radicar en bloque ante la compañía"
#           " aseguradora."
#       )
#     elif "torre a" in p_low:
#       d = len(
#           df[(df["torre"] == "Torre A") & (df["inmueble_afectado"] == "Sí")]
#       )
#       resp = (
#           f"La Torre A (5 pisos) registra {d} inmuebles con reportes de"
#           " afectaciones en proceso de verificación."
#       )
#     elif "torre b" in p_low:
#       d = len(
#           df[(df["torre"] == "Torre B") & (df["inmueble_afectado"] == "Sí")]
#       )
#       resp = (
#           f"La Torre B (5 pisos) registra {d} inmuebles con reportes de"
#           " afectaciones en proceso de verificación."
#       )
#     elif "torre c" in p_low:
#       d = len(
#           df[(df["torre"] == "Torre C") & (df["inmueble_afectado"] == "Sí")]
#       )
#       resp = (
#           f"La Torre C (6 pisos) registra {d} inmuebles con reportes de"
#           " afectaciones en proceso de verificación."
#       )
#     elif (
#         "piscina" in p_low
#         or "parqueadero" in p_low
#         or "gradas" in p_low
#         or "comunes" in p_low
#     ):
#       resp = (
#           "Las zonas comunes (gradas, piscina, pasillos y parqueaderos) cuentan"
#           " con evaluación técnica preliminar que no compromete la estabilidad"
#           " general."
#       )
#     else:
#       resp = (
#           "Su inquietud ha sido registrada. Por favor consulte las pestañas"
#           " del sistema para mayor detalle técnico y legal."
#       )
# 
#     st.session_state.mensajes.append({"role": "assistant", "content": resp})
#     with st.chat_message("assistant"):
#       st.write(resp)
# 
# # -------------------------------------------------------------
# # BANNER INSTITUCIONAL DE HABEAS DATA (LEGAL COLOMBIA)
# # -------------------------------------------------------------
# st.markdown(
#     """
#     <div class="legal-card">
#         <div class="legal-title">Marco de Protección de Datos Personales (Ley 1581 de 2012 / Decreto 1377 de 2013)</div>
#         <p class="legal-text">
#             El Conjunto Residencial Prados del Refugio, en calidad de Responsable del Tratamiento de Datos, garantiza que la información recolectada mediante los censos de diagnóstico post-sismo se encuentra amparada bajo el principio de finalidad estricta. Los datos personales de contacto, identificación y fotografías serán utilizados única y exclusivamente para la atención de la emergencia, la radicación del expediente formal ante la compañía aseguradora y la coordinación de las brigadas de auxilio, resguardando la confidencialidad y el derecho fundamental al Habeas Data de todos los copropietarios y residentes.
#         </p>
#     </div>
# """,
#     unsafe_allow_html=True,
# )